### ISSUE TITLE
Presence indicator

### ISSUE THREAD

**Issue by OxMarco** [Slenderman00/grindr-access#2]
Currently working on the XMPP integration side, do you know how to show the profile as online?

**Comment by Slenderman00** [comment]
It might be using the xmpp acks to check if a user is online.

**Comment by OxMarco** [comment]
tried but without success, I think they are using an API call to set user presence and location

**Comment by Slenderman00** [comment]
Okey, have you tried intercepting the applications traffic?

**Comment by OxMarco** [comment]
No, the app shuts down if it detects tampering with the server certificate (typical of a listener proxy present). The only way to fix it would be to disassemble the app and patch the certificate signature.

**Comment by Slenderman00** [comment]
Just use Frida to disable the SSL pinning

**Comment by OxMarco** [comment]
I'm on iOS, will check if I can get it to work on an emulator

**Comment by OxMarco** [comment]
Btw you can find my code [here](https://github.com/OxMarco/AI-dating-helper/blob/master/grindr/grindr/xmpp.py), I went a bit further and created an AI autoresponder
